### PR TITLE
Uploading sandcastle.py to bucket

### PR DESCRIPTION
**Pull request by GerbenJavado**
Sometimes uploading is allowed even when directory listening isn't. This line checks for that as well and uploading sandcastle.py is pretty harmless. Furthermore if the upload succeeds it can be manually removed.

### CODE REVIEW

**Comment by yasinS** [comment]
Hi @GerbenJavado, thanks very much for the contribution and PR on Sandcastle! 🙂 

Nice idea – wondering if we could build this into a command-line argument (maybe with a `-u` flag), and upload a "test" plaintext file containing something like the below, just in case of any concerns arising from an upload:

```
------------------------------------------------
Responsible disclosure test upload
------------------------------------------------
```

Would be great to hear your thoughts, and thanks again!

**Comment by GerbenJavado** [comment]
Seems better honestly, this is more of a "dirty" version. Has gotten me one bucket where this was the case already though.

**Comment by GerbenJavado** [comment]
On a second note: don't name it test but something completly random like: ahjkhdncnzncklsls. To make sure you don't overwrite any files.

**Comment by yasinS** [comment]
@GerbenJavado Nice that it got a result before! Always good to check upload permissions, especially on known company buckets. 

Definitely, good point. Using random text with a prefix (e.g. "`responsible-disclosure-[random].txt` or "`test-upload-[random].txt`") should be good with this kind of approach; hopefully successful uploads are followed up on and then deleted if not applicable.

**Comment by GerbenJavado** [comment]
With that approach you could even launch the rm command straight after. The file is 99,999% likely unique anyways.

**Comment by yasinS** [comment]
Yeah – this should ensure writeable buckets have been enumerated (and permissions tested) without creating any leftover files. Sounds good, will just need to double-check the filename if using `rm` and handle accordingly 🙂

**Comment by JR0ch17** [comment]
Hey @yasinS 
I second what @GerbenJavado said. It would definitely be a good idea to add an upload option to this tool.

**Comment by yasinS** [comment]
Hi @GerbenJavado and @JR0ch17,

Thanks for your support and feedback regarding this PR! Apologies for the inconvenience, but upon consideration I've decided to cease development of Sandcastle. @tomdev's [Bucketeers](https://github.com/tomdev/teh_s3_bucketeers/) project incorporates a much wider range of scanning prefixes, and is open to contribution PRs under the MIT License. 

Thanks again!

**Pull request closed without merging**
